language: node_js
node_js:
  - "8"
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm run dist
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
